* Dot-emacs

** Intro and motivation
This is emacs.d configuration. I use Emacs for basically everything. For taking notes I use org-mode, for coding stuff I use LSP-mode. I used to exploit it also as an e-mail client with notmuch (on [2021-09-30] I started to think about learning and using mutt instead, but I realized that it doesn't fit for my needs - on [2021-10-04] I decided to go back and use web-based e-mail client since I find useless and memory-consuming to have all my e-mails stored locally). I use Alpine since [2022-11-10], can see e-mails also within Emacs by opening a new terminal with vterm.
However, Emacs is love and hate: it has problems (everything does) but it gives me a huge flexibility and freedom to choose whatever workflow fits my needs the most.
** Configuration architecture
I have two different configurations: one for GUI usage, one for CLI. The idea is that the CLI version is quite minimal, it is concieved to be used with emacs-server and needs to be fast, reliable and aimed at editing files quickly (I also have some scripts that automatically starts emacs-server if it is not running in the background, whenever I start emacs from the command line). These two configurations are ~minimal.org~ (CLI configuration) and ~init.org~ (GUI configuration). Each of the two is just a series of ~require~, importing several modules that are located inside the ~modules~ folder. I decided to embrace this approach to maximize code reuse and maintainability (the minimal configuration requires only basic modules - e.g., org-mode, lsp). The reason why I did this was that I found myself modifying stuff in one of the two configurations and being forced to copy-and-paste stuff also in the other configuration. With the current architecture, this is no longer required.
#+begin_example
                                            +---> org-mode-setup.el
|-------------|                             |
|             |             |---------| ----+---> org-roam-setup.el
| minimal.org | --------->  | modules |     |
|             |             |---------|     +---> ...
|-------------|                 ^
                                |
|----------|                    |
|          |                    |
| init.org | -------------------+
|          |
|----------|
#+end_example
